name: evalai-challenge
on:
  push:
    branches: [challenge]
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [challenge]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure host config
        run: |
          echo '{
            "token": "${{ secrets.EVALAI_USER_AUTH_TOKEN }}",
            "team_pk": "${{ secrets.HOST_TEAM_PK }}",
            "evalai_host_url": "${{ secrets.EVALAI_HOST_URL }}"
          }' > host_config.json
          cat host_config.json  # Pour vérification (ne pas faire en prod)

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Version plus récente

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Validate challenge
        run: |
          python github/challenge_processing_script.py
        env:
          IS_VALIDATION: 'True'
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}  # Note: Utilisez GITHUB_TOKEN au lieu de AUTH_TOKEN

      - name: Create challenge
        if: ${{ github.event_name == 'push' }}
        run: |
          python github/challenge_processing_script.py
        env:
          IS_VALIDATION: 'False'
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
